In [1]:
import pandas as pd 
import os

data = 'student_placement_synthetic.csv'
df = pd.read_csv(data)
df

,branch,college_tier,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa
0,ECE,Tier-3,6.70,0,7.6,4.4,49.5,3.7,6.4,0.3,1,4,4,3,2,1,1,14.75
1,Chemical,Tier-2,5.70,0,5.4,7.9,72.0,8.3,6.3,1.9,0,4,0,0,0,0,0,NaN
2,EE,Tier-2,7.19,0,5.6,6.8,79.1,7.4,4.4,5.2,1,3,2,1,2,0,1,19.06
3,CE,Tier-2,6.48,0,5.2,3.1,48.4,5.0,1.1,6.7,1,4,3,0,0,0,0,NaN
4,CSE,Tier-2,6.71,1,5.9,4.7,61.2,4.3,2.7,2.8,1,2,0,3,0,1,1,13.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,IT,Tier-3,6.08,0,3.1,5.4,67.4,4.3,9.1,3.8,2,3,2,0,0,3,0,NaN
99996,IT,Tier-3,7.46,0,4.8,6.8,59.5,7.6,5.6,2.4,1,2,3,0,1,0,1,16.58
99997,EE,Tier-2,7.94,0,4.9,9.1,55.1,6.1,3.5,5.2,0,2,1,0,1,2,1,17.24
99998,ME,Tier-3,6.63,0,5.0,8.0,65.0,5.7,6.2,0.2,1,4,2,0,0,1,1,17.01
99999,ECE,Tier-1,7.00,0,2.8,5.3,64.5,5.7,5.7,3.4,0,2,2,2,0,1,1,14.98

In [2]:
df2 = df.copy()
df2

,branch,college_tier,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa
0,ECE,Tier-3,6.70,0,7.6,4.4,49.5,3.7,6.4,0.3,1,4,4,3,2,1,1,14.75
1,Chemical,Tier-2,5.70,0,5.4,7.9,72.0,8.3,6.3,1.9,0,4,0,0,0,0,0,NaN
2,EE,Tier-2,7.19,0,5.6,6.8,79.1,7.4,4.4,5.2,1,3,2,1,2,0,1,19.06
3,CE,Tier-2,6.48,0,5.2,3.1,48.4,5.0,1.1,6.7,1,4,3,0,0,0,0,NaN
4,CSE,Tier-2,6.71,1,5.9,4.7,61.2,4.3,2.7,2.8,1,2,0,3,0,1,1,13.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,IT,Tier-3,6.08,0,3.1,5.4,67.4,4.3,9.1,3.8,2,3,2,0,0,3,0,NaN
99996,IT,Tier-3,7.46,0,4.8,6.8,59.5,7.6,5.6,2.4,1,2,3,0,1,0,1,16.58
99997,EE,Tier-2,7.94,0,4.9,9.1,55.1,6.1,3.5,5.2,0,2,1,0,1,2,1,17.24
99998,ME,Tier-3,6.63,0,5.0,8.0,65.0,5.7,6.2,0.2,1,4,2,0,0,1,1,17.01
99999,ECE,Tier-1,7.00,0,2.8,5.3,64.5,5.7,5.7,3.4,0,2,2,2,0,1,1,14.98

In [3]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   branch                     100000 non-null  object
 1   college_tier               100000 non-null  object
 2   cgpa                       100000 non-null  float64
 3   backlogs                   100000 non-null  int64
 4   coding_skills              100000 non-null  float64
 5   dsa_score                  100000 non-null  float64
 6   aptitude_score             100000 non-null  float64
 7   communication_skills       100000 non-null  float64
 8   ml_knowledge               100000 non-null  float64
 9   system_design              100000 non-null  float64
 10  internships                100000 non-null  int64
 11  projects_count             100000 non-null  int64
 12  certifications             100000 non-null  int64
 13  hackathons                 100000 non-null  int64
 14  open_source_contributions  100000 non-null  int64
 15  extracurriculars           100000 non-null  int64
 16  placement_status           100000 non-null  int64
 17  salary_package_lpa         68475 non-null   float64
dtypes: float64(8), int64(8), object(2)
memory usage: 13.7+ MB

In [4]:
df.columns.tolist()

['branch',
 'college_tier',
 'cgpa',
 'backlogs',
 'coding_skills',
 'dsa_score',
 'aptitude_score',
 'communication_skills',
 'ml_knowledge',
 'system_design',
 'internships',
 'projects_count',
 'certifications',
 'hackathons',
 'open_source_contributions',
 'extracurriculars',
 'placement_status',
 'salary_package_lpa']

In [5]:
df.isnull().sum()

branch                           0
college_tier                     0
cgpa                             0
backlogs                         0
coding_skills                    0
dsa_score                        0
aptitude_score                   0
communication_skills             0
ml_knowledge                     0
system_design                    0
internships                      0
projects_count                   0
certifications                   0
hackathons                       0
open_source_contributions        0
extracurriculars                 0
placement_status                 0
salary_package_lpa           31525
dtype: int64

In [6]:
df2.duplicated().sum()

np.int64(0)

In [7]:
df2["salary_available"] = df2["placement_status"].astype(int)
df2["salary_package_lpa"] = df2["salary_package_lpa"].where(
    df["placement_status"] == 1, other=float("nan")
)
df2

,branch,college_tier,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa,salary_available
0,ECE,Tier-3,6.70,0,7.6,4.4,49.5,3.7,6.4,0.3,1,4,4,3,2,1,1,14.75,1
1,Chemical,Tier-2,5.70,0,5.4,7.9,72.0,8.3,6.3,1.9,0,4,0,0,0,0,0,NaN,0
2,EE,Tier-2,7.19,0,5.6,6.8,79.1,7.4,4.4,5.2,1,3,2,1,2,0,1,19.06,1
3,CE,Tier-2,6.48,0,5.2,3.1,48.4,5.0,1.1,6.7,1,4,3,0,0,0,0,NaN,0
4,CSE,Tier-2,6.71,1,5.9,4.7,61.2,4.3,2.7,2.8,1,2,0,3,0,1,1,13.42,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,IT,Tier-3,6.08,0,3.1,5.4,67.4,4.3,9.1,3.8,2,3,2,0,0,3,0,NaN,0
99996,IT,Tier-3,7.46,0,4.8,6.8,59.5,7.6,5.6,2.4,1,2,3,0,1,0,1,16.58,1
99997,EE,Tier-2,7.94,0,4.9,9.1,55.1,6.1,3.5,5.2,0,2,1,0,1,2,1,17.24,1
99998,ME,Tier-3,6.63,0,5.0,8.0,65.0,5.7,6.2,0.2,1,4,2,0,0,1,1,17.01,1
99999,ECE,Tier-1,7.00,0,2.8,5.3,64.5,5.7,5.7,3.4,0,2,2,2,0,1,1,14.98,1

In [8]:
from sklearn.preprocessing import MinMaxScaler
tech_cols = [
    "coding_skills",
    "dsa_score",
    "ml_knowledge",
    "system_design",
    "aptitude_score",
    "certifications"
]


scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df2[tech_cols])

df_scaled = pd.DataFrame(df_scaled, columns=tech_cols)

df2["tech_skill"] = df_scaled.mean(axis=1)

In [9]:
soft_cols = ['communication_skills','extracurriculars']
scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df2[soft_cols])

df_scaled = pd.DataFrame(df_scaled, columns=soft_cols)

df2["soft_skill"] = df_scaled.mean(axis=1)

In [10]:
practical_cols = ['internships','open_source_contributions','hackathons','projects_count']
scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df2[practical_cols])

df_scaled = pd.DataFrame(df_scaled, columns=practical_cols)

df2["practical_skill"] = df_scaled.mean(axis=1)

In [11]:
acad_cols = ["cgpa", "backlogs"]

scaler = MinMaxScaler()
scaled = scaler.fit_transform(df2[acad_cols])

df2["cgpa_scaled"] = scaled[:, 0]
df2["backlogs_scaled"] = scaled[:, 1]
df2["academic_points"] = (
    0.7 * df2["cgpa_scaled"] +
    0.3 * (1 - df2["backlogs_scaled"])
)

In [12]:
df2

,branch,college_tier,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,...,extracurriculars,placement_status,salary_package_lpa,salary_available,tech_skill,soft_skill,practical_skill,cgpa_scaled,backlogs_scaled,academic_points
0,ECE,Tier-3,6.70,0,7.6,4.4,49.5,3.7,6.4,0.3,...,1,1,14.75,1,0.524977,0.316667,0.783333,0.450000,0.000000,0.615000
1,Chemical,Tier-2,5.70,0,5.4,7.9,72.0,8.3,6.3,1.9,...,0,0,NaN,0,0.454259,0.405556,0.200000,0.283333,0.000000,0.498333
2,EE,Tier-2,7.19,0,5.6,6.8,79.1,7.4,4.4,5.2,...,0,1,19.06,1,0.559051,0.355556,0.566667,0.531667,0.000000,0.672167
3,CE,Tier-2,6.48,0,5.2,3.1,48.4,5.0,1.1,6.7,...,0,0,NaN,0,0.430833,0.222222,0.283333,0.413333,0.000000,0.589333
4,CSE,Tier-2,6.71,1,5.9,4.7,61.2,4.3,2.7,2.8,...,1,1,13.42,1,0.336759,0.350000,0.433333,0.451667,0.333333,0.516167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,IT,Tier-3,6.08,0,3.1,5.4,67.4,4.3,9.1,3.8,...,3,0,NaN,0,0.517454,0.683333,0.316667,0.346667,0.000000,0.542667
99996,IT,Tier-3,7.46,0,4.8,6.8,59.5,7.6,5.6,2.4,...,0,1,16.58,1,0.518403,0.366667,0.308333,0.576667,0.000000,0.703667
99997,EE,Tier-2,7.94,0,4.9,9.1,55.1,6.1,3.5,5.2,...,2,1,17.24,1,0.482014,0.616667,0.225000,0.656667,0.000000,0.759667
99998,ME,Tier-3,6.63,0,5.0,8.0,65.0,5.7,6.2,0.2,...,1,1,17.01,1,0.487454,0.427778,0.283333,0.438333,0.000000,0.606833
99999,ECE,Tier-1,7.00,0,2.8,5.3,64.5,5.7,5.7,3.4,...,1,1,14.98,1,0.440671,0.427778,0.266667,0.500000,0.000000,0.650000

In [13]:
tier_map = {'Tier-1': 1, 'Tier-2': 2, 'Tier-3': 3}
df2['college_tier'] = df2['college_tier'].map(tier_map)

# Verify
print(df2['college_tier'].value_counts())

college_tier
3    45222
2    39910
1    14868
Name: count, dtype: int64

In [14]:
df2 = pd.get_dummies(df2, columns=['branch'], drop_first=True)


branch_cols = df2.filter(like='branch').columns
df2[branch_cols] = df2[branch_cols].astype(int)

In [15]:
raw_cols = [
    'coding_skills', 'dsa_score', 'ml_knowledge',
    'system_design', 'aptitude_score', 'certifications',
    'communication_skills', 'extracurriculars',
    'internships', 'projects_count', 'hackathons',
    'open_source_contributions', 'cgpa', 'backlogs'
]
df2 = df2.drop(columns=raw_cols)

print("Remaining columns:", df2.columns.tolist())
print("Shape:", df2.shape)

Remaining columns: ['college_tier', 'placement_status', 'salary_package_lpa', 'salary_available', 'tech_skill', 'soft_skill', 'practical_skill', 'cgpa_scaled', 'backlogs_scaled', 'academic_points', 'branch_CSE', 'branch_Chemical', 'branch_ECE', 'branch_EE', 'branch_IT', 'branch_ME']
Shape: (100000, 16)

In [16]:
df_clean1 = df2
df_clean1

,college_tier,placement_status,salary_package_lpa,salary_available,tech_skill,soft_skill,practical_skill,cgpa_scaled,backlogs_scaled,academic_points,branch_CSE,branch_Chemical,branch_ECE,branch_EE,branch_IT,branch_ME
0,3,1,14.75,1,0.524977,0.316667,0.783333,0.450000,0.000000,0.615000,0,0,1,0,0,0
1,2,0,NaN,0,0.454259,0.405556,0.200000,0.283333,0.000000,0.498333,0,1,0,0,0,0
2,2,1,19.06,1,0.559051,0.355556,0.566667,0.531667,0.000000,0.672167,0,0,0,1,0,0
3,2,0,NaN,0,0.430833,0.222222,0.283333,0.413333,0.000000,0.589333,0,0,0,0,0,0
4,2,1,13.42,1,0.336759,0.350000,0.433333,0.451667,0.333333,0.516167,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,3,0,NaN,0,0.517454,0.683333,0.316667,0.346667,0.000000,0.542667,0,0,0,0,1,0
99996,3,1,16.58,1,0.518403,0.366667,0.308333,0.576667,0.000000,0.703667,0,0,0,0,1,0
99997,2,1,17.24,1,0.482014,0.616667,0.225000,0.656667,0.000000,0.759667,0,0,0,1,0,0
99998,3,1,17.01,1,0.487454,0.427778,0.283333,0.438333,0.000000,0.606833,0,0,0,0,0,1
99999,1,1,14.98,1,0.440671,0.427778,0.266667,0.500000,0.000000,0.650000,0,0,1,0,0,0

In [17]:
df_clean1.to_csv('data_clean(1).csv', index = False)